name: Resume Requirements

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Login to Registry
        run: docker login --username=${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }} crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com

      - name: Mirrors
        run: |
          docker pull ghcr.io/browserless/chromium:latest
          docker tag ghcr.io/browserless/chromium:latest crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/chromium:latest
          docker push crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/chromium:latest

          docker pull minio/minio:latest
          docker tag minio/minio:latest crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/minio:latest
          docker push crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/minio:latest

          docker pull postgres:16-alpine
          docker tag postgres:16-alpine crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/postgres:16-alpine
          docker push crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/postgres:16-alpine
