name: Server Requirements

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Login to Registry
        run: docker login --username=${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }} crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com

      - name: Mirrors
        run: |
          docker pull mongodb/mongodb-community-server:latest
          docker tag mongodb/mongodb-community-server:latest crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/mongodb-community-server:latest
          docker push crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/mongodb-community-server:latest

          # docker pull easytier/easytier:latest
          # docker tag easytier/easytier:latest crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/easytier:latest
          # docker push crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/easytier:latest

          # docker pull containrrr/watchtower:latest
          # docker tag containrrr/watchtower:latest crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/watchtower:latest
          # docker push crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/watchtower:latest

          

          # docker pull nginx:latest
          # docker tag nginx:latest crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/nginx:latest
          # docker push crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/nginx:latest

          # docker pull alpine:latest
          # docker tag alpine:latest crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/alpine:latest
          # docker push crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/alpine:latest

          # docker pull portainer/portainer-ce:latest
          # docker tag portainer/portainer-ce:latest crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/portainer-ce:latest
          # docker push crpi-ofh9eows662r8dot.cn-beijing.personal.cr.aliyuncs.com/mirror6/portainer-ce:latest
